/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthPurgatoryRouteImport } from './routes/_auth/purgatory'
import { Route as AuthInitializeRouteImport } from './routes/_auth/initialize'
import { Route as AuthLeagueRouteRouteImport } from './routes/_auth/_league/route'
import { Route as AuthLeagueIndexRouteImport } from './routes/_auth/_league/index'
import { Route as AuthLeagueTradesRouteImport } from './routes/_auth/_league/trades'
import { Route as AuthLeagueAdminRouteRouteImport } from './routes/_auth/_league/admin/route'
import { Route as AuthLeagueDeckDeckIdRouteImport } from './routes/_auth/_league/deck/$deckId'
import { Route as AuthLeagueUserUserIdDecksRouteImport } from './routes/_auth/_league/user/$userId/decks'
import { Route as AuthLeagueUserUserIdCollectionRouteImport } from './routes/_auth/_league/user/$userId/collection'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPurgatoryRoute = AuthPurgatoryRouteImport.update({
  id: '/purgatory',
  path: '/purgatory',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInitializeRoute = AuthInitializeRouteImport.update({
  id: '/initialize',
  path: '/initialize',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLeagueRouteRoute = AuthLeagueRouteRouteImport.update({
  id: '/_league',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLeagueIndexRoute = AuthLeagueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLeagueRouteRoute,
} as any)
const AuthLeagueTradesRoute = AuthLeagueTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AuthLeagueRouteRoute,
} as any)
const AuthLeagueAdminRouteRoute = AuthLeagueAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthLeagueRouteRoute,
} as any)
const AuthLeagueDeckDeckIdRoute = AuthLeagueDeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => AuthLeagueRouteRoute,
} as any)
const AuthLeagueUserUserIdDecksRoute =
  AuthLeagueUserUserIdDecksRouteImport.update({
    id: '/user/$userId/decks',
    path: '/user/$userId/decks',
    getParentRoute: () => AuthLeagueRouteRoute,
  } as any)
const AuthLeagueUserUserIdCollectionRoute =
  AuthLeagueUserUserIdCollectionRouteImport.update({
    id: '/user/$userId/collection',
    path: '/user/$userId/collection',
    getParentRoute: () => AuthLeagueRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthLeagueIndexRoute
  '/login': typeof LoginRoute
  '/initialize': typeof AuthInitializeRoute
  '/purgatory': typeof AuthPurgatoryRoute
  '/admin': typeof AuthLeagueAdminRouteRoute
  '/trades': typeof AuthLeagueTradesRoute
  '/deck/$deckId': typeof AuthLeagueDeckDeckIdRoute
  '/user/$userId/collection': typeof AuthLeagueUserUserIdCollectionRoute
  '/user/$userId/decks': typeof AuthLeagueUserUserIdDecksRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthLeagueIndexRoute
  '/login': typeof LoginRoute
  '/initialize': typeof AuthInitializeRoute
  '/purgatory': typeof AuthPurgatoryRoute
  '/admin': typeof AuthLeagueAdminRouteRoute
  '/trades': typeof AuthLeagueTradesRoute
  '/deck/$deckId': typeof AuthLeagueDeckDeckIdRoute
  '/user/$userId/collection': typeof AuthLeagueUserUserIdCollectionRoute
  '/user/$userId/decks': typeof AuthLeagueUserUserIdDecksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/_league': typeof AuthLeagueRouteRouteWithChildren
  '/_auth/initialize': typeof AuthInitializeRoute
  '/_auth/purgatory': typeof AuthPurgatoryRoute
  '/_auth/_league/admin': typeof AuthLeagueAdminRouteRoute
  '/_auth/_league/trades': typeof AuthLeagueTradesRoute
  '/_auth/_league/': typeof AuthLeagueIndexRoute
  '/_auth/_league/deck/$deckId': typeof AuthLeagueDeckDeckIdRoute
  '/_auth/_league/user/$userId/collection': typeof AuthLeagueUserUserIdCollectionRoute
  '/_auth/_league/user/$userId/decks': typeof AuthLeagueUserUserIdDecksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/initialize'
    | '/purgatory'
    | '/admin'
    | '/trades'
    | '/deck/$deckId'
    | '/user/$userId/collection'
    | '/user/$userId/decks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/initialize'
    | '/purgatory'
    | '/admin'
    | '/trades'
    | '/deck/$deckId'
    | '/user/$userId/collection'
    | '/user/$userId/decks'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/_league'
    | '/_auth/initialize'
    | '/_auth/purgatory'
    | '/_auth/_league/admin'
    | '/_auth/_league/trades'
    | '/_auth/_league/'
    | '/_auth/_league/deck/$deckId'
    | '/_auth/_league/user/$userId/collection'
    | '/_auth/_league/user/$userId/decks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/purgatory': {
      id: '/_auth/purgatory'
      path: '/purgatory'
      fullPath: '/purgatory'
      preLoaderRoute: typeof AuthPurgatoryRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/initialize': {
      id: '/_auth/initialize'
      path: '/initialize'
      fullPath: '/initialize'
      preLoaderRoute: typeof AuthInitializeRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_league': {
      id: '/_auth/_league'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLeagueRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_league/': {
      id: '/_auth/_league/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthLeagueIndexRouteImport
      parentRoute: typeof AuthLeagueRouteRoute
    }
    '/_auth/_league/trades': {
      id: '/_auth/_league/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthLeagueTradesRouteImport
      parentRoute: typeof AuthLeagueRouteRoute
    }
    '/_auth/_league/admin': {
      id: '/_auth/_league/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthLeagueAdminRouteRouteImport
      parentRoute: typeof AuthLeagueRouteRoute
    }
    '/_auth/_league/deck/$deckId': {
      id: '/_auth/_league/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof AuthLeagueDeckDeckIdRouteImport
      parentRoute: typeof AuthLeagueRouteRoute
    }
    '/_auth/_league/user/$userId/decks': {
      id: '/_auth/_league/user/$userId/decks'
      path: '/user/$userId/decks'
      fullPath: '/user/$userId/decks'
      preLoaderRoute: typeof AuthLeagueUserUserIdDecksRouteImport
      parentRoute: typeof AuthLeagueRouteRoute
    }
    '/_auth/_league/user/$userId/collection': {
      id: '/_auth/_league/user/$userId/collection'
      path: '/user/$userId/collection'
      fullPath: '/user/$userId/collection'
      preLoaderRoute: typeof AuthLeagueUserUserIdCollectionRouteImport
      parentRoute: typeof AuthLeagueRouteRoute
    }
  }
}

interface AuthLeagueRouteRouteChildren {
  AuthLeagueAdminRouteRoute: typeof AuthLeagueAdminRouteRoute
  AuthLeagueTradesRoute: typeof AuthLeagueTradesRoute
  AuthLeagueIndexRoute: typeof AuthLeagueIndexRoute
  AuthLeagueDeckDeckIdRoute: typeof AuthLeagueDeckDeckIdRoute
  AuthLeagueUserUserIdCollectionRoute: typeof AuthLeagueUserUserIdCollectionRoute
  AuthLeagueUserUserIdDecksRoute: typeof AuthLeagueUserUserIdDecksRoute
}

const AuthLeagueRouteRouteChildren: AuthLeagueRouteRouteChildren = {
  AuthLeagueAdminRouteRoute: AuthLeagueAdminRouteRoute,
  AuthLeagueTradesRoute: AuthLeagueTradesRoute,
  AuthLeagueIndexRoute: AuthLeagueIndexRoute,
  AuthLeagueDeckDeckIdRoute: AuthLeagueDeckDeckIdRoute,
  AuthLeagueUserUserIdCollectionRoute: AuthLeagueUserUserIdCollectionRoute,
  AuthLeagueUserUserIdDecksRoute: AuthLeagueUserUserIdDecksRoute,
}

const AuthLeagueRouteRouteWithChildren = AuthLeagueRouteRoute._addFileChildren(
  AuthLeagueRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLeagueRouteRoute: typeof AuthLeagueRouteRouteWithChildren
  AuthInitializeRoute: typeof AuthInitializeRoute
  AuthPurgatoryRoute: typeof AuthPurgatoryRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLeagueRouteRoute: AuthLeagueRouteRouteWithChildren,
  AuthInitializeRoute: AuthInitializeRoute,
  AuthPurgatoryRoute: AuthPurgatoryRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
