/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedLeagueIndexRouteImport } from './routes/_authenticated/league/index'
import { Route as AuthenticatedLeagueLeagueIdRouteRouteImport } from './routes/_authenticated/league/$leagueId/route'
import { Route as AuthenticatedLeagueLeagueIdIndexRouteImport } from './routes/_authenticated/league/$leagueId/index'
import { Route as AuthenticatedLeagueLeagueIdTradesRouteImport } from './routes/_authenticated/league/$leagueId/trades'
import { Route as AuthenticatedLeagueLeagueIdDecksUserIdRouteImport } from './routes/_authenticated/league/$leagueId/decks.$userId'
import { Route as AuthenticatedLeagueLeagueIdCollectionUserIdRouteImport } from './routes/_authenticated/league/$leagueId/collection.$userId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeagueIndexRoute =
  AuthenticatedLeagueIndexRouteImport.update({
    id: '/league/',
    path: '/league/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeagueLeagueIdRouteRoute =
  AuthenticatedLeagueLeagueIdRouteRouteImport.update({
    id: '/league/$leagueId',
    path: '/league/$leagueId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeagueLeagueIdIndexRoute =
  AuthenticatedLeagueLeagueIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLeagueLeagueIdRouteRoute,
  } as any)
const AuthenticatedLeagueLeagueIdTradesRoute =
  AuthenticatedLeagueLeagueIdTradesRouteImport.update({
    id: '/trades',
    path: '/trades',
    getParentRoute: () => AuthenticatedLeagueLeagueIdRouteRoute,
  } as any)
const AuthenticatedLeagueLeagueIdDecksUserIdRoute =
  AuthenticatedLeagueLeagueIdDecksUserIdRouteImport.update({
    id: '/decks/$userId',
    path: '/decks/$userId',
    getParentRoute: () => AuthenticatedLeagueLeagueIdRouteRoute,
  } as any)
const AuthenticatedLeagueLeagueIdCollectionUserIdRoute =
  AuthenticatedLeagueLeagueIdCollectionUserIdRouteImport.update({
    id: '/collection/$userId',
    path: '/collection/$userId',
    getParentRoute: () => AuthenticatedLeagueLeagueIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/league/$leagueId': typeof AuthenticatedLeagueLeagueIdRouteRouteWithChildren
  '/league/': typeof AuthenticatedLeagueIndexRoute
  '/league/$leagueId/trades': typeof AuthenticatedLeagueLeagueIdTradesRoute
  '/league/$leagueId/': typeof AuthenticatedLeagueLeagueIdIndexRoute
  '/league/$leagueId/collection/$userId': typeof AuthenticatedLeagueLeagueIdCollectionUserIdRoute
  '/league/$leagueId/decks/$userId': typeof AuthenticatedLeagueLeagueIdDecksUserIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/league': typeof AuthenticatedLeagueIndexRoute
  '/league/$leagueId/trades': typeof AuthenticatedLeagueLeagueIdTradesRoute
  '/league/$leagueId': typeof AuthenticatedLeagueLeagueIdIndexRoute
  '/league/$leagueId/collection/$userId': typeof AuthenticatedLeagueLeagueIdCollectionUserIdRoute
  '/league/$leagueId/decks/$userId': typeof AuthenticatedLeagueLeagueIdDecksUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/league/$leagueId': typeof AuthenticatedLeagueLeagueIdRouteRouteWithChildren
  '/_authenticated/league/': typeof AuthenticatedLeagueIndexRoute
  '/_authenticated/league/$leagueId/trades': typeof AuthenticatedLeagueLeagueIdTradesRoute
  '/_authenticated/league/$leagueId/': typeof AuthenticatedLeagueLeagueIdIndexRoute
  '/_authenticated/league/$leagueId/collection/$userId': typeof AuthenticatedLeagueLeagueIdCollectionUserIdRoute
  '/_authenticated/league/$leagueId/decks/$userId': typeof AuthenticatedLeagueLeagueIdDecksUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/league/$leagueId'
    | '/league/'
    | '/league/$leagueId/trades'
    | '/league/$leagueId/'
    | '/league/$leagueId/collection/$userId'
    | '/league/$leagueId/decks/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/league'
    | '/league/$leagueId/trades'
    | '/league/$leagueId'
    | '/league/$leagueId/collection/$userId'
    | '/league/$leagueId/decks/$userId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/league/$leagueId'
    | '/_authenticated/league/'
    | '/_authenticated/league/$leagueId/trades'
    | '/_authenticated/league/$leagueId/'
    | '/_authenticated/league/$leagueId/collection/$userId'
    | '/_authenticated/league/$leagueId/decks/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/league/': {
      id: '/_authenticated/league/'
      path: '/league'
      fullPath: '/league/'
      preLoaderRoute: typeof AuthenticatedLeagueIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/league/$leagueId': {
      id: '/_authenticated/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof AuthenticatedLeagueLeagueIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/league/$leagueId/': {
      id: '/_authenticated/league/$leagueId/'
      path: '/'
      fullPath: '/league/$leagueId/'
      preLoaderRoute: typeof AuthenticatedLeagueLeagueIdIndexRouteImport
      parentRoute: typeof AuthenticatedLeagueLeagueIdRouteRoute
    }
    '/_authenticated/league/$leagueId/trades': {
      id: '/_authenticated/league/$leagueId/trades'
      path: '/trades'
      fullPath: '/league/$leagueId/trades'
      preLoaderRoute: typeof AuthenticatedLeagueLeagueIdTradesRouteImport
      parentRoute: typeof AuthenticatedLeagueLeagueIdRouteRoute
    }
    '/_authenticated/league/$leagueId/decks/$userId': {
      id: '/_authenticated/league/$leagueId/decks/$userId'
      path: '/decks/$userId'
      fullPath: '/league/$leagueId/decks/$userId'
      preLoaderRoute: typeof AuthenticatedLeagueLeagueIdDecksUserIdRouteImport
      parentRoute: typeof AuthenticatedLeagueLeagueIdRouteRoute
    }
    '/_authenticated/league/$leagueId/collection/$userId': {
      id: '/_authenticated/league/$leagueId/collection/$userId'
      path: '/collection/$userId'
      fullPath: '/league/$leagueId/collection/$userId'
      preLoaderRoute: typeof AuthenticatedLeagueLeagueIdCollectionUserIdRouteImport
      parentRoute: typeof AuthenticatedLeagueLeagueIdRouteRoute
    }
  }
}

interface AuthenticatedLeagueLeagueIdRouteRouteChildren {
  AuthenticatedLeagueLeagueIdTradesRoute: typeof AuthenticatedLeagueLeagueIdTradesRoute
  AuthenticatedLeagueLeagueIdIndexRoute: typeof AuthenticatedLeagueLeagueIdIndexRoute
  AuthenticatedLeagueLeagueIdCollectionUserIdRoute: typeof AuthenticatedLeagueLeagueIdCollectionUserIdRoute
  AuthenticatedLeagueLeagueIdDecksUserIdRoute: typeof AuthenticatedLeagueLeagueIdDecksUserIdRoute
}

const AuthenticatedLeagueLeagueIdRouteRouteChildren: AuthenticatedLeagueLeagueIdRouteRouteChildren =
  {
    AuthenticatedLeagueLeagueIdTradesRoute:
      AuthenticatedLeagueLeagueIdTradesRoute,
    AuthenticatedLeagueLeagueIdIndexRoute:
      AuthenticatedLeagueLeagueIdIndexRoute,
    AuthenticatedLeagueLeagueIdCollectionUserIdRoute:
      AuthenticatedLeagueLeagueIdCollectionUserIdRoute,
    AuthenticatedLeagueLeagueIdDecksUserIdRoute:
      AuthenticatedLeagueLeagueIdDecksUserIdRoute,
  }

const AuthenticatedLeagueLeagueIdRouteRouteWithChildren =
  AuthenticatedLeagueLeagueIdRouteRoute._addFileChildren(
    AuthenticatedLeagueLeagueIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLeagueLeagueIdRouteRoute: typeof AuthenticatedLeagueLeagueIdRouteRouteWithChildren
  AuthenticatedLeagueIndexRoute: typeof AuthenticatedLeagueIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLeagueLeagueIdRouteRoute:
    AuthenticatedLeagueLeagueIdRouteRouteWithChildren,
  AuthenticatedLeagueIndexRoute: AuthenticatedLeagueIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
