/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedLeagueLeagueIdRouteRouteImport } from './routes/_authenticated/league.$leagueId/route'
import { Route as AuthenticatedLeagueLeagueIdShopRouteImport } from './routes/_authenticated/league.$leagueId/shop'
import { Route as AuthenticatedLeagueLeagueIdCollectionPlayerIdRouteImport } from './routes/_authenticated/league.$leagueId/collection.$playerId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeagueLeagueIdRouteRoute =
  AuthenticatedLeagueLeagueIdRouteRouteImport.update({
    id: '/league/$leagueId',
    path: '/league/$leagueId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeagueLeagueIdShopRoute =
  AuthenticatedLeagueLeagueIdShopRouteImport.update({
    id: '/shop',
    path: '/shop',
    getParentRoute: () => AuthenticatedLeagueLeagueIdRouteRoute,
  } as any)
const AuthenticatedLeagueLeagueIdCollectionPlayerIdRoute =
  AuthenticatedLeagueLeagueIdCollectionPlayerIdRouteImport.update({
    id: '/collection/$playerId',
    path: '/collection/$playerId',
    getParentRoute: () => AuthenticatedLeagueLeagueIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/league/$leagueId': typeof AuthenticatedLeagueLeagueIdRouteRouteWithChildren
  '/league/$leagueId/shop': typeof AuthenticatedLeagueLeagueIdShopRoute
  '/league/$leagueId/collection/$playerId': typeof AuthenticatedLeagueLeagueIdCollectionPlayerIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/league/$leagueId': typeof AuthenticatedLeagueLeagueIdRouteRouteWithChildren
  '/league/$leagueId/shop': typeof AuthenticatedLeagueLeagueIdShopRoute
  '/league/$leagueId/collection/$playerId': typeof AuthenticatedLeagueLeagueIdCollectionPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/league/$leagueId': typeof AuthenticatedLeagueLeagueIdRouteRouteWithChildren
  '/_authenticated/league/$leagueId/shop': typeof AuthenticatedLeagueLeagueIdShopRoute
  '/_authenticated/league/$leagueId/collection/$playerId': typeof AuthenticatedLeagueLeagueIdCollectionPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/league/$leagueId'
    | '/league/$leagueId/shop'
    | '/league/$leagueId/collection/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/league/$leagueId'
    | '/league/$leagueId/shop'
    | '/league/$leagueId/collection/$playerId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/league/$leagueId'
    | '/_authenticated/league/$leagueId/shop'
    | '/_authenticated/league/$leagueId/collection/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/league/$leagueId': {
      id: '/_authenticated/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof AuthenticatedLeagueLeagueIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/league/$leagueId/shop': {
      id: '/_authenticated/league/$leagueId/shop'
      path: '/shop'
      fullPath: '/league/$leagueId/shop'
      preLoaderRoute: typeof AuthenticatedLeagueLeagueIdShopRouteImport
      parentRoute: typeof AuthenticatedLeagueLeagueIdRouteRoute
    }
    '/_authenticated/league/$leagueId/collection/$playerId': {
      id: '/_authenticated/league/$leagueId/collection/$playerId'
      path: '/collection/$playerId'
      fullPath: '/league/$leagueId/collection/$playerId'
      preLoaderRoute: typeof AuthenticatedLeagueLeagueIdCollectionPlayerIdRouteImport
      parentRoute: typeof AuthenticatedLeagueLeagueIdRouteRoute
    }
  }
}

interface AuthenticatedLeagueLeagueIdRouteRouteChildren {
  AuthenticatedLeagueLeagueIdShopRoute: typeof AuthenticatedLeagueLeagueIdShopRoute
  AuthenticatedLeagueLeagueIdCollectionPlayerIdRoute: typeof AuthenticatedLeagueLeagueIdCollectionPlayerIdRoute
}

const AuthenticatedLeagueLeagueIdRouteRouteChildren: AuthenticatedLeagueLeagueIdRouteRouteChildren =
  {
    AuthenticatedLeagueLeagueIdShopRoute: AuthenticatedLeagueLeagueIdShopRoute,
    AuthenticatedLeagueLeagueIdCollectionPlayerIdRoute:
      AuthenticatedLeagueLeagueIdCollectionPlayerIdRoute,
  }

const AuthenticatedLeagueLeagueIdRouteRouteWithChildren =
  AuthenticatedLeagueLeagueIdRouteRoute._addFileChildren(
    AuthenticatedLeagueLeagueIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLeagueLeagueIdRouteRoute: typeof AuthenticatedLeagueLeagueIdRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLeagueLeagueIdRouteRoute:
    AuthenticatedLeagueLeagueIdRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
